In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [2]:
df=pd.read_csv('final-crime.csv')

In [3]:
df.dropna(inplace=True)

In [4]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10642 entries, 0 to 10643
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   STATE/UT                10642 non-null  object 
 1   DISTRICT                10642 non-null  object 
 2   YEAR                    10642 non-null  float64
 3   MURDER                  10642 non-null  float64
 4   ATTEMPT TO MURDER       10642 non-null  float64
 5   RAPE                    10642 non-null  float64
 6   KIDNAPPING & ABDUCTION  10642 non-null  float64
 7   ROBBERY                 10642 non-null  float64
 8   VIOLENCE                10642 non-null  float64
 9   CHEATING                10642 non-null  float64
 10  CRIME ON WOMEN          10642 non-null  float64
 11  HUMAN TRAFFICKING       10642 non-null  float64
dtypes: float64(10), object(2)
memory usage: 1.1+ MB


In [6]:
df

STATE/UT       DISTRICT    YEAR  MURDER  ATTEMPT TO MURDER  \
0      ANDHRA PRADESH       ADILABAD  2001.0   101.0               77.0   
1      ANDHRA PRADESH      ANANTAPUR  2001.0   151.0              126.0   
2      ANDHRA PRADESH       CHITTOOR  2001.0   101.0               59.0   
3      ANDHRA PRADESH       CUDDAPAH  2001.0    80.0               54.0   
4      ANDHRA PRADESH  EAST GODAVARI  2001.0    82.0               68.0   
...               ...            ...     ...     ...                ...   
10639        Delhi UT      Vigilance  2014.0     0.0                0.0   
10640        Delhi UT           West  2014.0    55.0               83.0   
10641     Lakshadweep    Lakshadweep  2014.0     0.0                0.0   
10642      Puducherry       Karaikal  2014.0     6.0                1.0   
10643      Puducherry     Puducherry  2014.0    19.0               17.0   

        RAPE  KIDNAPPING & ABDUCTION  ROBBERY  VIOLENCE  CHEATING  \
0      100.0                    92.0    637.0    1248.0     121.0   
1       46.0                   106.0    939.0    1788.0      84.0   
2       54.0                   118.0   1697.0    2286.0     251.0   
3       40.0                    50.0    448.0     983.0      51.0   
4       46.0                    98.0   2504.0    1359.0     273.0   
...      ...                     ...      ...       ...       ...   
10639    0.0                     0.0      0.0       0.0       0.0   
10640  352.0                   251.0   1615.0     257.0      87.0   
10641    1.0                     1.0      0.0       1.0       0.0   
10642    3.0                     3.0      2.0       5.0       1.0   
10643    8.0                     7.0     20.0      12.0       6.0   

       CRIME ON WOMEN  HUMAN TRAFFICKING  
0               374.0                0.0  
1               303.0                0.0  
2               395.0                0.0  
3               238.0                0.0  
4               426.0                0.0  
...               ...                ...  
10639             0.0                0.0  
10640          2524.0             9404.0  
10641            20.0               15.0  
10642            37.0               33.0  
10643            91.0              391.0  

[10642 rows x 12 columns]

In [7]:
df['STATE/UT'] = df['STATE/UT'].str.lower()
df['DISTRICT'] = df['DISTRICT'].str.lower()

In [8]:
le = LabelEncoder()
df["State_Label"] = le.fit_transform(df["STATE/UT"])
df["District_Label"] = le.fit_transform(df["DISTRICT"])


df = df.drop(columns=["STATE/UT", "DISTRICT"])

In [9]:
y=df[df.columns[0:10]]
x=df[df.columns[10:]]

In [10]:
x

State_Label  District_Label
0                2               3
1                2              35
2                2             184
3                2             204
4                2             261
...            ...             ...
10639           11             925
10640           11             946
10641           20             530
10642           28             449
10643           28             695

[10642 rows x 2 columns]

In [11]:
y.drop('YEAR',axis=1,inplace=True)
y

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


MURDER  ATTEMPT TO MURDER   RAPE  KIDNAPPING & ABDUCTION  ROBBERY  \
0       101.0               77.0  100.0                    92.0    637.0   
1       151.0              126.0   46.0                   106.0    939.0   
2       101.0               59.0   54.0                   118.0   1697.0   
3        80.0               54.0   40.0                    50.0    448.0   
4        82.0               68.0   46.0                    98.0   2504.0   
...       ...                ...    ...                     ...      ...   
10639     0.0                0.0    0.0                     0.0      0.0   
10640    55.0               83.0  352.0                   251.0   1615.0   
10641     0.0                0.0    1.0                     1.0      0.0   
10642     6.0                1.0    3.0                     3.0      2.0   
10643    19.0               17.0    8.0                     7.0     20.0   

       VIOLENCE  CHEATING  CRIME ON WOMEN  HUMAN TRAFFICKING  
0        1248.0     121.0           374.0                0.0  
1        1788.0      84.0           303.0                0.0  
2        2286.0     251.0           395.0                0.0  
3         983.0      51.0           238.0                0.0  
4        1359.0     273.0           426.0                0.0  
...         ...       ...             ...                ...  
10639       0.0       0.0             0.0                0.0  
10640     257.0      87.0          2524.0             9404.0  
10641       1.0       0.0            20.0               15.0  
10642       5.0       1.0            37.0               33.0  
10643      12.0       6.0            91.0              391.0  

[10642 rows x 9 columns]

In [ ]:
for i in range(y.shape[0]):
  sum=y.iloc[i].sum(axis=0)
  for j in range(y.shape[1]):
    val=y.iloc[i,j]/sum
    if(val>0.25):
      y.iloc[i,j]=1
    else:
      y.iloc[i,j]=0
  print(i)

In [12]:
y=pd.read_csv('crime-final.csv')

In [13]:
y

Unnamed: 0  MURDER  ATTEMPT TO MURDER  RAPE  KIDNAPPING & ABDUCTION  \
0               0     0.0                0.0   0.0                     0.0   
1               1     0.0                0.0   0.0                     0.0   
2               2     0.0                0.0   0.0                     0.0   
3               3     0.0                0.0   0.0                     0.0   
4               4     0.0                0.0   0.0                     0.0   
...           ...     ...                ...   ...                     ...   
10637       10639     0.0                0.0   0.0                     0.0   
10638       10640     0.0                0.0   0.0                     0.0   
10639       10641     0.0                0.0   0.0                     0.0   
10640       10642     0.0                0.0   0.0                     0.0   
10641       10643     0.0                0.0   0.0                     0.0   

       ROBBERY  VIOLENCE  CHEATING  CRIME ON WOMEN  HUMAN TRAFFICKING  
0          0.0       1.0       0.0             0.0                0.0  
1          1.0       1.0       0.0             0.0                0.0  
2          1.0       1.0       0.0             0.0                0.0  
3          0.0       1.0       0.0             0.0                0.0  
4          1.0       1.0       0.0             0.0                0.0  
...        ...       ...       ...             ...                ...  
10637      0.0       0.0       0.0             0.0                0.0  
10638      0.0       0.0       0.0             0.0                1.0  
10639      0.0       0.0       0.0             1.0                1.0  
10640      0.0       0.0       0.0             1.0                1.0  
10641      0.0       0.0       0.0             0.0                1.0  

[10642 rows x 10 columns]

In [14]:
import numpy as np
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.svm import LinearSVC
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_recall_curve
from sklearn.metrics import average_precision_score
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import RidgeClassifier
from sklearn.metrics import f1_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.pipeline import make_pipeline


In [ ]:
from keras.models import Sequential
from keras.layers import Activation, Dense

In [ ]:
n_inputs=x.shape[1]
n_outputs=y.shape[1]

In [ ]:
# define the model
model = Sequential()
model.add(Dense(20, input_dim=n_inputs, kernel_initializer='he_uniform', activation='relu'))
model.add(Dense(n_outputs, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam')

In [ ]:
model.fit(x, y, verbose=0, epochs=10)

In [15]:
from tensorflow import keras
model=keras.models.load_model("/content/statewise_model.h5")

In [18]:
evl=model.evaluate(x,y)

333/333 [==============================] - 1s 2ms/step - loss: -87908024.0000


In [19]:
temp=model.predict(x, verbose=0)

In [ ]:
temp[0]

array([1.        , 0.05645746, 0.00880389, 0.0041983 , 0.01106999,
       0.47355863, 0.39514682, 0.22984613, 0.40749836, 0.38872927],
      dtype=float32)

In [ ]:
temp[0]

array([1.        , 0.05645746, 0.00880389, 0.0041983 , 0.01106999,
       0.47355863, 0.39514682, 0.22984613, 0.40749836, 0.38872927],
      dtype=float32)

In [ ]:
for i in range(100):
  print(temp[i].sum())

In [ ]:
x

State_Label  District_Label
0                2               3
1                2              31
2                2             280
3                2             301
4                2             431
...            ...             ...
10639           19            1566
10640           19            1593
10641           37             904
10642           54             820
10643           54            1174

[10642 rows x 2 columns]

In [ ]:
data=[['ANDHRA PRADESH','ADILABAD']]
tee = pd.DataFrame(data, columns=['STATE/UT', 'DISTRICT'])
tee

STATE/UT  DISTRICT
0  ANDHRA PRADESH  ADILABAD

In [ ]:
tee

State_Label  District_Label
0            0               0

In [ ]:
tee.iloc[0,0]=2
tee.iloc[0,1]=3

In [ ]:
tee

STATE/UT DISTRICT
0        2        3

In [ ]:
tee["DISTRICT"] = tee["DISTRICT"].astype(str).astype(float)

In [ ]:
testt=model.predict(tee, verbose=0)

In [ ]:
testt

array([[1.0000000e+00, 1.9322393e-02, 7.1776292e-04, 3.9178587e-02,
        1.0384795e-02, 5.7658601e-01, 5.4038882e-01, 2.7559468e-01,
        3.5802418e-01, 2.9584128e-01]], dtype=float32)

In [ ]:
temp[0][3]

0.019039484

In [ ]:
model.save('statewise_model.h5')

In [ ]:
from google.colab import files
files.download("/content/statewise_model")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
!zip -r /content/statewise_model.zip /content/statewise_model

  adding: content/statewise_model/ (stored 0%)
  adding: content/statewise_model/saved_model.pb (deflated 87%)
  adding: content/statewise_model/assets/ (stored 0%)
  adding: content/statewise_model/variables/ (stored 0%)
  adding: content/statewise_model/variables/variables.data-00000-of-00001 (deflated 47%)
  adding: content/statewise_model/variables/variables.index (deflated 58%)
  adding: content/statewise_model/keras_metadata.pb (deflated 84%)


In [ ]:
from google.colab import files
files.download("/content/statewise_model.zip")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
ss=pd.read_csv('final-crime.csv')

In [ ]:
ss

Unnamed: 0        STATE/UT       DISTRICT    YEAR  MURDER  \
0               0  ANDHRA PRADESH       ADILABAD  2001.0   101.0   
1               1  ANDHRA PRADESH      ANANTAPUR  2001.0   151.0   
2               2  ANDHRA PRADESH       CHITTOOR  2001.0   101.0   
3               3  ANDHRA PRADESH       CUDDAPAH  2001.0    80.0   
4               4  ANDHRA PRADESH  EAST GODAVARI  2001.0    82.0   
...           ...             ...            ...     ...     ...   
10639       10639        Delhi UT      Vigilance  2014.0     0.0   
10640       10640        Delhi UT           West  2014.0    55.0   
10641       10641     Lakshadweep    Lakshadweep  2014.0     0.0   
10642       10642      Puducherry       Karaikal  2014.0     6.0   
10643       10643      Puducherry     Puducherry  2014.0    19.0   

       ATTEMPT TO MURDER   RAPE  KIDNAPPING & ABDUCTION  ROBBERY  VIOLENCE  \
0                   77.0  100.0                    92.0    637.0    1248.0   
1                  126.0   46.0                   106.0    939.0    1788.0   
2                   59.0   54.0                   118.0   1697.0    2286.0   
3                   54.0   40.0                    50.0    448.0     983.0   
4                   68.0   46.0                    98.0   2504.0    1359.0   
...                  ...    ...                     ...      ...       ...   
10639                0.0    0.0                     0.0      0.0       0.0   
10640               83.0  352.0                   251.0   1615.0     257.0   
10641                0.0    1.0                     1.0      0.0       1.0   
10642                1.0    3.0                     3.0      2.0       5.0   
10643               17.0    8.0                     7.0     20.0      12.0   

       CHEATING  CRIME ON WOMEN  HUMAN TRAFFICKING  
0         121.0           374.0                0.0  
1          84.0           303.0                0.0  
2         251.0           395.0                0.0  
3          51.0           238.0                0.0  
4         273.0           426.0                0.0  
...         ...             ...                ...  
10639       0.0             0.0                0.0  
10640      87.0          2524.0             9404.0  
10641       0.0            20.0               15.0  
10642       1.0            37.0               33.0  
10643       6.0            91.0              391.0  

[10644 rows x 13 columns]

In [ ]:
ss['STATE/UT'] = ss['STATE/UT'].str.lower()
ss['DISTRICT'] = ss['DISTRICT'].str.lower()

In [ ]:
ss.dropna(inplace=True)
ss1=ss[ss.columns[1:3]]


In [ ]:
ss1

STATE/UT       DISTRICT
0      andhra pradesh       adilabad
1      andhra pradesh      anantapur
2      andhra pradesh       chittoor
3      andhra pradesh       cuddapah
4      andhra pradesh  east godavari
...               ...            ...
10639        delhi ut      vigilance
10640        delhi ut           west
10641     lakshadweep    lakshadweep
10642      puducherry       karaikal
10643      puducherry     puducherry

[10642 rows x 2 columns]

In [ ]:
x

State_Label  District_Label
0                2               3
1                2              31
2                2             280
3                2             301
4                2             431
...            ...             ...
10639           19            1566
10640           19            1593
10641           37             904
10642           54             820
10643           54            1174

[10642 rows x 2 columns]

In [ ]:
dict = {k.lower(): v for k, v in state_dict.items()}

In [ ]:
dict

In [ ]:
dictionary={}

In [ ]:
dictionary[ss1.iloc[0,0]]=1;
dictionary

In [ ]:
len(ss1)
x.shape[0]

10642

In [ ]:
for i in range(x.shape[0]):
  for j in range(x.shape[1]):
    dictionary[ss1.iloc[i,j]]=x.iloc[i,j]

In [ ]:
print(dictionary)

{'andhra pradesh': 2, 'adilabad': 3, 'anantapur': 35, 'chittoor': 184, 'cuddapah': 204, 'east godavari': 261, 'guntakal rly.': 326, 'guntur': 327, 'hyderabad city': 359, 'karimnagar': 454, 'khammam': 469, 'krishna': 514, 'kurnool': 520, 'mahaboobnagar': 552, 'medak': 576, 'nalgonda': 623, 'nellore': 639, 'nizamabad': 643, 'prakasham': 693, 'ranga reddy': 737, 'secunderabad rly.': 781, 'srikakulam': 840, 'vijayawada': 927, 'vijayawada rly.': 930, 'visakha rural': 934, 'visakhapatnam': 935, 'vizianagaram': 936, 'warangal': 941, 'west godavari': 947, 'total': 887, 'arunachal pradesh': 3, 'changlang': 168, 'dibang valley': 249, 'kameng east': 435, 'kameng west': 436, 'lohit': 537, 'papum pare': 669, 'siang east': 798, 'siang upper': 799, 'siang west': 800, 'subansiri lower': 848, 'subansiri upper': 849, 'tawang': 862, 'tirap': 882, 'assam': 4, 'barpeta': 87, 'bongaigaon': 137, 'c.i.d.': 151, 'cachar': 152, 'darrang': 220, 'dhemaji': 244, 'dhubri': 247, 'dibrugarh': 250, 'g.r.p.': 284, 'goa

In [ ]:
import joblib
loaded_model = joblib.load('finalized_model_statewise.sav')
crime_list={'MURDER': 0,'ATTEMPT TO MURDER': 1,'RAPE': 2, 'KIDNAPPING': 3, 'ROBBERY':4,'VIOLENCE':5,'CHEATING':6,'CRIME ON WOMEN': 7, 'HUMAN TRAFFICKING': 8}
data=[['ANDHRA PRADESH','ADILABAD']]
test = pd.DataFrame(data, columns=['State_Label', 'District_Label'])
test['State_Label'] = test['State_Label'].str.lower()
test['District_Label'] = test['District_Label'].str.lower()

if not test.iloc[0,0] in dictionary:
  print('0')
else:
  test.iloc[0,0]=dictionary[test.iloc[0][0]]

if not test.iloc[0,1] in dictionary:
  print('0')
else:
  test.iloc[0,1]=dictionary[test.iloc[0][1]]
test = test.apply(lambda col:pd.to_numeric(col, errors='coerce'))
ans=loaded_model.predict(test,verbose=0)
print(ans[0][crime_list['MURDER']])
  

0.29932094


In [ ]:
tee.iloc[0,0]=state_dict[tee.iloc[0][0]]
tee.iloc[0,1]=state_dict[tee.iloc[0][1]]




In [ ]:
tee = tee.apply(lambda col:pd.to_numeric(col, errors='coerce'))

In [ ]:
tee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   State_Label     1 non-null      int64
 1   District_Label  1 non-null      int64
dtypes: int64(2)
memory usage: 144.0 bytes


In [ ]:
out=model.predict(tee, verbose=0)

In [ ]:
out

array([[2.5117224e-02, 2.3384851e-05, 1.0034964e-05, 1.9039478e-02,
        7.5996292e-01, 5.2506387e-01, 5.3663429e-02, 4.8663545e-02,
        2.3770610e-02]], dtype=float32)

In [ ]:
arr = numpy.array(state_dict)